# Generated by Django 4.2.2 on 2023-07-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=124, unique=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(max_length=124)),
                ("descirption", models.TextField()),
                ("hash", models.CharField(max_length=124, unique=True)),
                ("blob_ref", models.CharField(max_length=124, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("priority", models.IntegerField(default=0)),
            ],
        ),
    ]
